package vn.com.orchestration.foodios.constant;

public class ErrorConstant {
    public static final String SYSTEM_ERROR = "6800";
    public static final String SYSTEM_ERROR_MESSAGE = "System Error";
    public static final String TIMEOUT_ERROR = "0600";
    public static final String AUTHORIZATION_ERROR = "3200";
    public static final String AUTHORITIES_ERROR = "You are not authorized for this action";
    public static final String TIMEOUT_ERROR_MESSAGE = "Timeout";
    public static final String RECORD_NOT_FOUND = "1407";
    public static final String ROLE_NOT_FOUND = "Role not found";
    public static final String AUTHORITIES_NOT_FOUND = "Authorities not found";
    public static final String ROUTE_NOT_FOUND = "Route with Id %s not found";
    public static final String OPERATION_POINT_NOT_FOUND = "Operation point with Id %s not found";
    public static final String PROVINCE_NOT_FOUND = "Province with Id %s not found";
    public static final String SEAT_NOT_FOUND = "Seats not found";
    public static final String ROUTE_POINT_NOT_FOUND = "Route Point not found";
    public static final String VEHICLE_NOT_FOUND = "Vehicle not found";
    public static final String VEHICLE_NOT_FOUND_BY_ID = "Vehicle with Id %s not found";
    public static final String ROUTE_SEAT_NOT_FOUND = "Rout Seat with Route Id %s is not exists";
    public static final String RECORD_NOT_FOUND_MESSAGE = "Record not found";
    public static final String SUCCESS_CODE = "0000";
    public static final String SUCCESS_MESSAGE = "Success";
    public static final String DRIVER_NOT_FOUND_MESSAGE = "Driver Profile not found";
    public static final String USER_NOT_FOUND_MESSAGE = "User Profile not found";
    public static final String MEMBERSHIP_NOT_FOUND_MESSAGE = "Membership Profile not found";
    public static final String INVALID_HTTP_REQUEST_RESOURCE_ERROR = "4000";
    public static final String INVALID_HTTP_REQUEST_RESOURCE_ERROR_MESSAGE = "Resource %s path is not exists";
    public static final String INVALID_INPUT_ERROR = "0310";
    public static final String INVALID_USER_MESSAGE = "Invalid userId";
    public static final String SEAT_NOT_AVAILABLE = "Seat %s is not available";
    public static final String INVALID_INPUT_MESSAGE = "Invalid Input";
    public static final String INVALID_REQUEST_TIMESTAMP = "5186";
    public static final String DUPLICATE_ERROR = "9400";
    public static final String MERCHANT_EXISTS = "Merchant %s already exists";
    public static final String PHONE_NUMBER_EXISTS = "Phone Number already exists";

    public static final String DUPLICATE_OPERATION_POINT_MESSAGE = "Operation point with this code already exists";
    public static final String DUPLICATE_PROVINCE = "Province is already exists by %s";
    public static final String DUPLICATE_USER_ROLE_MESSAGE = "User already has this role";
    public static final String ROLE_EXISTS_ERROR = "Role with %s already exists";
    public static final String PERMISSION_EXISTS_ERROR = "Authorities with %s already exists";
    public static final String INVALID_PAGE_SIZE = "pageSize must be in [1..100]";
    public static final String INVALID_PAGE_NUMBER = "pageNumber must be >= 1";
    public static final String INVALID_SEAT_NO = "seatNos must not be empty";
    public static final String DUPLICATE_VEHICLE = "Vehicle is already exists by %s";
    public static final String ROUTE_SEAT_EXIST = "Route Seat with routeId %s already created";
    public static final String DUPLICATE_ROUTE_ASSIGNMENT = "Route Assignment with routeId %s already exists";
    public static final String RECORD_EXISTS = "Record is already existed";
    public static final String INVALID_START_TIME = "Planned Start Time must be before Planned End Time";
    public static final String INVALID_STOP_ORDER = "operationOrder must be positive & unique";
    public static final String INVALID_PLANNED_TIME = "Invalid planned arrival or departure time";
    public static final String INVALID_SEARCH_TIME = "From Time must be before To Time";

    // Auth messages
    public static final String USERNAME_EXISTS_MESSAGE = "Username already exists";
    public static final String EMAIL_EXISTS_MESSAGE = "Email already exists";
    public static final String PHONE_NUMBER_EXISTS_MESSAGE = "Phone number already exists";
    public static final String INVALID_USERNAME_OR_PASSWORD_MESSAGE = "Invalid username or password";
    public static final String USER_NOT_ACTIVE_MESSAGE = "User is not active";
    public static final String OPERATION_NOT_ALLOWED = "4030";
    public static final String EMAIL_NOT_VERIFIED_MESSAGE = "Email is not verified";
    public static final String OTP_EXPIRED_OR_NOT_FOUND_MESSAGE = "OTP expired or not found";
    public static final String INVALID_OTP_MESSAGE = "Invalid OTP";
    public static final String EMAIL_EXISTS = "Email already exists";

    public static final String USER_EXISTS = "User already exists";
    public static final String TOO_MANY_ATTEMPTS_MESSAGE = "Too many attempts";
    public static final String REFRESH_TOKEN_NOT_FOUND_MESSAGE = "Refresh token not found";
    public static final String INVALID_REFRESH_TOKEN_MESSAGE = "Invalid refresh token";
    public static final String REFRESH_TOKEN_EXPIRED_MESSAGE = "Refresh token expired";
    public static final String FILE_UPLOAD_ERROR = "9310";
    public static final String FILE_UPLOAD_ERROR_MESSAGE = "File upload failed";
    public static final String INVALID_FILE_MESSAGE = "Invalid file";
    public static final String STORE_NOT_FOUND_MESSAGE = "Store not found";
    public static final String CATEGORY_NOT_FOUND_MESSAGE = "Category not found";
    public static final String PRODUCT_NAME_EXISTS_MESSAGE = "Product already exists in store";
    public static final String PRODUCT_SKU_EXISTS_MESSAGE = "Product SKU already exists in store";
    public static final String PRODUCT_SLUG_EXISTS_MESSAGE = "Product slug already exists in store";
    public static final String MERCHANT_ACCESS_DENIED_MESSAGE = "You are not allowed to manage this merchant";
    public static final String ADMIN_ACCESS_DENIED_MESSAGE = "You are not allowed to manage merchants";
    public static final String MERCHANT_EXISTS_MESSAGE = "Merchant with %s already exists";
    public static final String MERCHANT_SLUG_EXISTS_MESSAGE = "Merchant slug already exists";
    public static final String STORE_SLUG_EXISTS_MESSAGE = "Store slug already exists";
    public static final String ROLE_EXISTS_MESSAGE = "Role already exists";
    public static final String AUTHORITY_EXISTS_MESSAGE = "Authority already exists";
    public static final String ROLE_NOT_FOUND_MESSAGE = "Role not found";
    public static final String AUTHORITY_NOT_FOUND_MESSAGE = "Authority not found";
    public static final String USER_ROLE_UPDATED_MESSAGE = "User role updated";
    public static final String ROLE_AUTHORITIES_UPDATED_MESSAGE = "Role authorities updated";
}
